# Generated by Django 5.0.6 on 2026-07-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orientation',
            field=models.CharField(blank=True, choices=[('straight', 'Straight'), ('gay', 'Gay')], default='', help_text="User's romantic interest preference (straight or gay).", max_length=10),
        ),
    ]
