# Generated by Django 5.0.6 on 2026-07-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesubscription',
            old_name='stripe_payment_id',
            new_name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='profilesubscription',
            name='initial_payment_cents',
            field=models.PositiveIntegerField(default=20000, help_text='Initial payment in cents (e.g. 20000 = $200.00)'),
        ),
        migrations.AddField(
            model_name='profilesubscription',
            name='recurring_price_cents',
            field=models.PositiveIntegerField(default=1500, help_text='Recurring monthly price in cents (e.g. 1500 = $15.00)'),
        ),
        migrations.AddField(
            model_name='profilesubscription',
            name='services_unlocked',
            field=models.BooleanField(default=False, help_text='True once initial payment is confirmed'),
        ),
        migrations.AddField(
            model_name='profilesubscription',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
