# Generated by Django 5.0.6 on 2026-08-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatmessage_image_alter_chatmessage_content_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, default='', help_text='Optional image file attached to the message', upload_to='chat_images/%Y/%m/%d/'),
        ),
    ]
