# Generated by Django 5.0.6 on 2026-08-03 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servicepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('tether', 'Tether'), ('usdt', 'USDT')], max_length=20)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('wallet_address', models.CharField(blank=True, default='', max_length=200)),
                ('tx_hash', models.CharField(blank=True, default='', help_text='Transaction hash provided by the user after paying', max_length=200)),
                ('purpose', models.CharField(blank=True, default='', help_text='e.g. subscription-14days, subscription-1month, service-Basic Massage', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
