# Generated by Django 5.0.6 on 2026-08-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cryptopayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.PositiveIntegerField(help_text='ID of the profile in profiles.js', unique=True)),
                ('profile_name', models.CharField(blank=True, default='', max_length=120)),
                ('initial_price_cents', models.PositiveIntegerField(default=20000, help_text='One-time initial unlock fee in cents (e.g. 20000 = $200.00)')),
                ('recurring_monthly_price_cents', models.PositiveIntegerField(default=3500, help_text='Recurring monthly price in cents (e.g. 3500 = $35.00)')),
                ('recurring_14day_price_cents', models.PositiveIntegerField(default=1400, help_text='Recurring 14-day price in cents (e.g. 1400 = $14.00)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['profile_id'],
            },
        ),
        migrations.AddField(
            model_name='profilesubscription',
            name='recurring_interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('14days', 'Every 14 days')], default='month', help_text='How often the recurring charge happens', max_length=20),
        ),
        migrations.AddField(
            model_name='profilesubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
