# Generated by Django 5.0.6 on 2026-07-08 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Stable identifier, e.g. 'free', 'premium-monthly'.", unique=True)),
                ('name', models.CharField(max_length=80)),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Price in cents (e.g. 1999 = $19.99).')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('interval', models.CharField(choices=[('none', 'One-time / N/A'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=10)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=120)),
                ('paypal_plan_id', models.CharField(blank=True, default='', max_length=120)),
                ('unlimited_likes', models.BooleanField(default=False)),
                ('unlimited_messaging', models.BooleanField(default=False)),
                ('advanced_filters', models.BooleanField(default=False)),
                ('verified_badge_priority', models.BooleanField(default=False)),
                ('profile_boost', models.BooleanField(default=False)),
                ('see_profile_viewers', models.BooleanField(default=False)),
                ('see_who_liked_you', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'price_cents'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='active', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=120)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=120)),
                ('paypal_subscription_id', models.CharField(blank=True, default='', max_length=120)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=10)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=200)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
